apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: epqe1r18o-go 
  janus-idp.io/tekton: epqe1r18o-go
  backstage.io/kubernetes-id: epqe1r18o-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: epqe1r18o-go
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml